### PR TITLE
[SKIP-PREVIEW] Greenkeeper/pa11y 5.0.1

### PR DESCRIPTION
**Pull request by robertparkinson**
### Change description
Pa11y released a new major version that had support for promises built in. This means we no longer need to use es6-promisfy. Getting this to work locally was simple enough and those changes are all in the a11y.ts file however to get it working using docker and on travis required updates to both the docker file and the travis file. This was to enable the downloading and running of google chrome which Pa11y now uses to run its tests. 

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled 
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent 

### Developer self-QA run statement

- [x] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by yarpo** [comment]
conflicted files

**Comment by yarpo** [comment]
This PR is very old. Do we still need it?

**Comment by robertparkinson** [comment]
I'd still like to get this merged at some point. We do need to upgrade to the latest version but @geek-soft wanted to have a proper look at it when there is time

**Comment by geek-soft** [comment]
Closing as https://github.com/hmcts/cmc-citizen-frontend/pull/641 supersedes it.

**Pull request closed without merging**
