### PR TITLE
Feature/ROC-7363-Bespoke-Dashboard

### PR DESCRIPTION
**Pull request by AlokDatta**
### JIRA link
https://tools.hmcts.net/jira/browse/ROC-7363

### Change description
Added code logic to identify bespoke event on the case and update the claimant/defendant dashboard accordingly.

### Work checklist

- [x] Unit tests added where applicable
- [x] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled 
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent 

### Developer self-QA run statement

- [x] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by shashisk97 — APPROVED** [review]
Please check coverage rest looks fine for me

**Review by santu412 — APPROVED** [review]

**Comment by sunilkumar-cts** [comment]
will be reopened when it is ready to be released

**Comment by AlokDatta** [comment]
Reopening as need to take update from the master. Will close afterwards.

**Comment by AlokDatta** [comment]
Closing. will reopen when ready for release.

**Comment by AlokDatta** [comment]
Reopening for demo deployment

**Pull request merged**
