### PR TITLE
ROC-8313 - Claims stuck in draft

### PR DESCRIPTION
**Pull request by santu412**
### JIRA link

ROC-8313

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled 
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent 

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by pradhap87 — APPROVED** [review]

**Review by pradhap87 — DISMISSED** [review]
one a11y test case is failing.

**Review by AlokDatta — APPROVED** [review]

**Review by shashisk97 — APPROVED** [review]
changes looks fine for me

**Comment by sunilkumar-cts** [comment]
will be reopened when it is ready to be released

**Comment by AlokDatta** [comment]
Reopening this pull request, as it is ready for merge to master

**Comment by sunilkumar-cts** [comment]
will be reopened

**Comment by AlokDatta** [comment]
reopening for release

**Pull request merged**
