### PR TITLE
ROC-8566 : Fixing code smell issues reported in citizen frontend

### PR DESCRIPTION
**Pull request by pradhap87**
### JIRA link

> [ROC-8566](https://tools.hmcts.net/jira/browse/ROC-8566)

### Change description

> Fixing code smell issues reported in citizen frontend
> https://sonarcloud.io/project/issues?id=cmc-citizen-frontend&resolved=false&severities=MAJOR

@AlokDatta is working on this PR

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled 
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent 

### Developer self-QA run statement

- [x] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by pradhap87** [comment]
Will be opening new one.

**Comment by AlokDatta** [comment]
Opening the PR as code smell issues has been picked up again,

**Review by yogendraU — APPROVED** [review]

**Review by ThirumuruganD — APPROVED** [review]

**Comment by AlokDatta** [comment]
Will reopen the PR once deployment is enabled.

**Comment by AlokDatta** [comment]
reopening as release has resumed

**Pull request merged**
