### PR TITLE
ROC-5404: disable bulk print requests for PRs

### PR DESCRIPTION
**Pull request by markry-kainos**
### JIRA link

https://tools.hmcts.net/jira/browse/ROC-5404

### Change description

Bulk print requests are stacking up! This will stop bulk print requests on PR functional tests.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by markry-kainos** [comment]
> is this really worth it?

Oh man...well...I do think it's better to isolate these PRs as much as poss tbh. 

But specifically for this PR we were asked to manage our bulk print requests, this seemed the only option to me. An automated purge is probably better but @nitinprabhu  said not coming anytime soon.

**Comment by timja** [comment]
@nitinprabhu do you think this is worth it? quite a few extra pods needing to be spun up for this on every PR

**Comment by markry-kainos** [comment]
> @nitinprabhu do you think this is worth it? quite a few extra pods needing to be spun up for this on every PR

1 extra pod :-D

**Comment by markry-kainos** [comment]
@nitinprabhu @timja another short-term cmc solution (until permanent automated cleanup in place) could also be to bin this PR and point our PRs to our new AAT AKS deployments (and disable bulk print here)...

**Comment by nitinprabhu** [comment]
We have already implemented a story to clean up files regularly on our FTP server which deletes all files which are uploaded past 12 hours. Also we have this story in backlog where services could pass a flag to say if the files needs to be uploaded to FTP or not https://tools.hmcts.net/jira/browse/BPS-580.

**Comment by markry-kainos** [comment]
> We have already implemented a story to clean up files regularly on our FTP server which deletes all files which are uploaded past 12 hours. Also we have this story in backlog where services could pass a flag to say if the files needs to be uploaded to FTP or not [tools.hmcts.net/jira/browse/BPS-580](https://tools.hmcts.net/jira/browse/BPS-580).
> @markry-kainos @timja

Thanks will close this PR

**Pull request closed without merging**
