### PR TITLE
OWSAP Errors fixed

### PR DESCRIPTION
**Pull request by AlokDatta**
### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Task list and task completeness checks updated
- [ ] Check and send page updated
- [ ] Routes, page content and page flows of new features are toggled 
- [ ] UI changes look good on mobile
- [ ] Required Google Analytics events are being sent 

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by pradhap87 — APPROVED** [review]

**Comment by AlokDatta** [comment]
Will reopen once start working

**Comment by AlokDatta** [comment]
Reopening

**Comment by pradhap87** [comment]
@AlokDatta i am closing this PR for cleaning some memory in the pipeline, please re-open this PR when ever you need it.

**Comment by AlokDatta** [comment]
reopening

**Comment by AlokDatta** [comment]
Closing the PR. Will reopen once we get a go ahead.

**Pull request closed without merging**
