### PR TITLE
ROC-8095-new-claim-fee-changes

### PR DESCRIPTION
**Pull request by AlokDatta**
### JIRA link
https://tools.hmcts.net/jira/browse/ROC-9085

### Change description
Changes made to the parameter 'channel' in fees-register api call to retrieve the latest claim fees.

Changes are lying behind the feature toggle - 'new-claim-fees'

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ThirumuruganD — APPROVED** [review]

**Comment by AlokDatta** [comment]
Closing as failing in AKS deploy

**Comment by AlokDatta** [comment]
Reopening

**Review by shashisk97 — APPROVED** [review]

**Comment by AlokDatta** [comment]
closing

**Comment by AlokDatta** [comment]
reopening

**Comment by AlokDatta** [comment]
closing

**Pull request closed without merging**
